name: Backup to S3

on:
  schedule:
    # 毎日12時(JST = UTC+9)に実行
    - cron: "00 03 * * *"
    # 手動実行のトリガーを追加
    workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. AWS CLIをセットアップ
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credintials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    # 3. 必要に応じてディレクトリを圧縮
    - name: Compress files
      run: tar -czvf backup.tar.gz data/

    # 4. 圧縮ファイルをS3にアップロード
    - name: Upload to S3
      run: aws s3 cp backup.tar.gz s3://urahomot-backup-bucket/backup-$(date +%Y-%m-%d).tar.gz
